### ISSUE TITLE
Secure REST API

### ISSUE THREAD

**Issue by JugglerX** [tshape/tshape#3]
Only allow authenticated users to perform an API call to get their own profile.

**Comment by angieellis** [comment]
Changes on add_api_auth branch. This was branched off of the more_user_fields branch

**Comment by JugglerX** [comment]
When i try to connect to the API i can see Authentication is required which is great.

Can you provide some information on how to authenticate?

**Comment by angieellis** [comment]
Send a request to the "api-token-auth/" endpoint with a "username" and "password" parameter in the header. It will return a token (as long as its an admin account) that you can use with any subsequent requests to the "api/" routes with the header "Token insertyourtokenhere".
