### ISSUE TITLE
Edit User Page

### ISSUE THREAD

**Issue by JugglerX** [tshape/tshape#4]
Once the firstname, lastname and job title have been added to the signup form.

Create a new edit user screen, where a user can update their personal info. This should be pretty standard.

* edit user page has the following fields
  * change username
  * change password
  * first name
  * last name
  * job title

* add an edit profile link to the header menu (when logged in)
* display users first last name in header menu (instead of email)

**Comment by angieellis** [comment]
Changes on more_user_fields branch
