### ISSUE TITLE
New URL Routes using username

### ISSUE THREAD

**Issue by JugglerX** [tshape/tshape#6]
Updating the URL's to be more friendly

/profiles/1/ -> /%username%/
We need a new route for editing the tshape: /%username%/edit
/profiles/1/edit -> /%username%/profile/edit

**Comment by angieellis** [comment]
Changes on more_user_fields branch

**Comment by JugglerX** [comment]
The new routes are better but not quite right. The users username should display the Tshape, not their profile (first name, last name) as the Tshape is the main thing associated with your account and the purpose of the app.

- A users public Tshape should be at /%username%
- A user editing their own Tshape should be something like /%username/edit
- A users public profile (first name, last name etc) should be at /%username/profile
- A user editing their own profile should be at /%username%/profile/edit

**Comment by angieellis** [comment]
fixed
