### ISSUE TITLE
Forgot Password/Password Reset

### ISSUE THREAD

**Issue by JugglerX** [tshape/tshape#7]
We need forgot your password and password reset functionality on the signup/login forms.

Implement the Django default functionality for this feature

**Comment by angieellis** [comment]
Changes on more_user_fields branch

**Comment by JugglerX** [comment]
I get this when I click the reset password link from the signup form
![screen shot 2016-12-28 at 1 44 20 pm](https://cloud.githubusercontent.com/assets/1386506/21532306/dbe8b8b0-cd03-11e6-9e42-ce7f295968f5.png)

**Comment by JugglerX** [comment]
have you tested the actual email functionality? Does it send you an email?
